### ISSUE TITLE
compilation error : 'serialize.h' file not found

### ISSUE THREAD

**Issue by pyrog** [glidernet/ogn-rf#13]
Hi,

As I haven't yet an Raspberry PI, I installed a Debian in a VirtualBox.

I try to `make` ogn-rf but I get the following message:
`./buffer.h:31:10: fatal error: 'serialize.h' file not found`

PS: initially, I just try use the build package and run `ogn-rf` and `ogg-decode` but I got `libjpeg.so.8: cannot open shared object file: No such file or directory`

The _funny_ thing is that libjpeg is only needed by the internal web server to provide status 😉

**Comment by kerel-fs** [comment]
Fixed by it 24b72ef, apparently some files were missing in the previous commit.
