### ISSUE TITLE
ogn-decode offline

### ISSUE THREAD

**Issue by nunojpg** [glidernet/ogn-rf#30]
Hi, Sometimes I have no internet connection and still want to check FLARM traffic. Can I do it offline?

**Comment by bencehari** [comment]
As I can see, the ogn-rf reads the decoded data from a file what the ogn-decode write on-the-fly, so when you lost connection and the ogn-decode timed out after a minute, there will be no more data.

It would be nice, if the ogn-decode doesn't stop writing the file after connection lost and/or there will be a "closed" decode library with an API, so we could pass the raw data to it and get the decoded data.

That would came with a big Thank You Guys! :)

**Comment by snip** [comment]
ogn-rf pass data to ogn-decode via a fifo file.
When internet connection is lost, messages are kept in memory and sent to OGN APRS servers once connection is up.
