### ISSUE TITLE
Where do I get version 0.2.7? / Different altitude reports to 0.2.6

### ISSUE THREAD

**Issue by hb9eue** [glidernet/ogn-rf#37]
Hi Devs

I have noticed that many receivers around here have updated to version 0.2.7, which I cannot find any download for.
Also those versions seem to report a different altitude than mine, which is clearly visible of you watch altitude graphs on https://glidertracker.de/

Has this version been discontinued? Which one is the official repository?

-Benoît-

**Comment by snip** [comment]
Hi Benoît,

0.2.7 is a beta version. It will be released after different update as 0.2.8.

Maybe have a look to this message: https://groups.google.com/d/msg/openglidernetwork/4UXG3Z4YqQo/CKwfNHgKCQAJ

If i remember well some versions of 0.2.7 automatically download this file.

**Comment by hb9eue** [comment]
I have seen receivers around mine are on Version 0.2.8-RPI-GPU. Same question again: Where can I find Version 0.2.8?

http://download.glidernet.org/ => LATEST is 0.2.6
This Github repository also is no further. Has there been a fork and development proceeding somewhere else?

**Comment by snip** [comment]
Here: https://github.com/pjalocha/ogn-rf-soapysdr

**Comment by hb9eue** [comment]
Hi, Thank you, that is 0.2.7, now my receiver reports the same altitude as the other 2.7 versions around. But where does Version 2.8 come from I see as example on the receiver Letzi and LSZF?
