### ISSUE TITLE
Is this project still going ?

### ISSUE THREAD

**Issue by ssozonoff** [glidernet/ogn-rf#47]
Hi,

I just wondered if this project is still going in terms of having OGN feeders in the wild. I have spent a couple of hours trying to get a feeder up and running on an RPi 4 but ogn-rf seems outdated and no longer compatible with the latest kernels and hardware. I have found all sorts of alternative explanations on the internet but not a single one working yet.

Thanks

**Comment by snip** [comment]
Hi Serge,

Yes it is working well.

A simple way to use it is to use my pi image available here: https://github.com/snip/OGN-receiver-RPI-image/

See u
--
Seb

**Comment by ssozonoff** [comment]
ok. I will have a look but ideally I am trying to integrate this into an existing ADS-B feeder stack so was hoping to create a Docker image. Thank you
