### ISSUE TITLE
Frequency offset in config file accepts only integer

### ISSUE THREAD

**Issue by dspreitz** [glidernet/ogn-rf#7]
The frequency offset in the config file only accepts integer values. When you enter a float, the offset is taken as zero.
Entering floats as an offset seems overly precise. Nevertheless, a conversion from dbl to int for that config parameter would increase program robustness.

**Comment by dspreitz** [comment]
I think this bug was closed with version 0.2.4??

**Comment by snip** [comment]
Unfortunately not. Only GeoidSepar was corrected.

**Comment by kerel-fs** [comment]
Fixed in a83d28b072ecf839925de249dce975f99264f50a (v0.2.5).
