### ISSUE TITLE
rtlsdr-flarm Rpi GPU version crash on Rpi2

### ISSUE THREAD

**Issue by snip** [glidernet/ogn-rf#9]
Complet OS crash on Rpi2.
As a workaround we can use non GPU version.

**Comment by massar** [comment]
Replicated that on a Rpi2 (same code ran fine-ish on a RPi1B).

Get a nice kernel crash and full lockup of Rpi2.

Unfortunately kernel crashes do not flush out over the serial port, only visible on HDMI, thus hard to get text out of that.

It could be the ogn-rf component or the ogn-decode component. Hard to debug this, as both are required to run each other (which in violates the GPL principle btw.... even if one uses a pipe, as the GPL component is required to do the function).

**Comment by snip** [comment]
Hi Joren,

Usage of GPU changed between RPi1 and RPi2. This part of the code need to be rewriten to works with RPi2.
As RPi2 works well without GPU offload this hasn't been pointed as a priority subject.

**Comment by kerel-fs** [comment]
Fixed in a83d28b, see https://github.com/glidernet/ogn-rf/blob/master/Changelog#L6.
